<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackageId>Orleans.EventSourcing.Kurrent</PackageId>
    <Authors>William Gunaratne</Authors>
    <Title>Kurrent for Microsoft Orleans Event-Sourcing</Title>
    <Description>Kurrent client implementation of log consistency provider for Microsoft Orleans EventSourcing.</Description>
    <RootNamespace>Orleans.EventSourcing.Kurrent</RootNamespace>
    <AnalysisLevel>latest-all</AnalysisLevel>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);OEK0001;OEK0002</NoWarn>
  </PropertyGroup>	
  <ItemGroup>
    <InternalsVisibleTo Include="Orleans.EventSourcing.Kurrent.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="KurrentDB.Client" />
    <PackageReference Include="Microsoft.Orleans.EventSourcing" />
    <PackageReference Include="OpenTelemetry.Api" />
  </ItemGroup>
</Project>